development:
  adapter: postgresql
  host: localhost
  database: waitlist-rails-server-dev
  encoding: unicode
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  host: localhost
  database: waitlist-rails-server-test
  encoding: unicode
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  host: localhost
  database: waitlist-rails-server-prod
  encoding: unicode
  pool: 5
  username:
  password:
